
package me.elaamiri.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankWebservice", targetNamespace = "http://webservice.elaamiri.me/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankWebservice {


    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "covert", targetNamespace = "http://webservice.elaamiri.me/", className = "me.elaamiri.proxy.Covert")
    @ResponseWrapper(localName = "covertResponse", targetNamespace = "http://webservice.elaamiri.me/", className = "me.elaamiri.proxy.CovertResponse")
    @Action(input = "http://webservice.elaamiri.me/BankWebservice/covertRequest", output = "http://webservice.elaamiri.me/BankWebservice/covertResponse")
    public double covert(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param code
     * @return
     *     returns me.elaamiri.proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://webservice.elaamiri.me/", className = "me.elaamiri.proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://webservice.elaamiri.me/", className = "me.elaamiri.proxy.GetAccountResponse")
    @Action(input = "http://webservice.elaamiri.me/BankWebservice/getAccountRequest", output = "http://webservice.elaamiri.me/BankWebservice/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<me.elaamiri.proxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://webservice.elaamiri.me/", className = "me.elaamiri.proxy.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://webservice.elaamiri.me/", className = "me.elaamiri.proxy.GetAccountsResponse")
    @Action(input = "http://webservice.elaamiri.me/BankWebservice/getAccountsRequest", output = "http://webservice.elaamiri.me/BankWebservice/getAccountsResponse")
    public List<Account> getAccounts();

}
